apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  namespace: nginx
  labels:
    app: nginx

spec:
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      namespace: nginx
      labels:
        app: nginx
        
    spec:
      containers:
      - name: nginx
        image: anirbanb13/devops-projects-images:latest
        ports: 
        - containerPort: 5000
        env:
          - name: OWM_API_KEY
            valueFrom:
              secretKeyRef:
                name: weather-app-secret
                key: OWM_API_KEY
