apiVersion: apps/v1
kind: Deployment
metadata: 
  name: weather-app-deployment
  namespace: weather-app
  labels:
    app: weather-app

spec:
  replicas: 4
  selector: 
    matchLabels:
      app: weather-app
  template:
    metadata:
      name: weather-app-pod
      namespace: weather-app
      labels:
        app: weather-app
        
    spec:
      containers:
      - name: weather-app
        image: anirbanb13/devops-projects-images:latest
        ports: 
        - containerPort: 5000
        env:
          - name: OWM_API_KEY
            valueFrom:
              secretKeyRef:
                name: weather-app-secret
                key: OWM_API_KEY
